//! Adversarial tests for AC5 — generated by the autobuilder Adversarial Agent.
//!
//! AC5 (MUST): "When deny_network:true is claimed and the trace contains >=1
//! connect event, verdict=block."
//!
//! These tests try to falsify the implementation against the English
//! description of AC5, not against the implementation itself. If any of these
//! fail, the implementation is weaker than the AC requires.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use session_trace_receipt::*;

fn ev(ts: u64, kind: &str) -> TraceEvent {
    TraceEvent {
        ts,
        r#type: kind.to_string(),
        pid: Some(99),
        comm: Some("worker".to_string()),
        file: None,
        path: None,
        flags: None,
    }
}

const fn deny_net_only() -> HardConstraints {
    HardConstraints {
        deny_network: true,
        deny_unsafe_runtime: false,
        max_subprocess_depth: None,
    }
}

// ---------------------------------------------------------------------------
// Strategy 1: Symmetric falsification.
// AC5 says "deny_network && >=1 connect -> block". The inverse: deny_network
// claimed but ZERO connect events must NOT yield block. This catches the
// stub `events.len() > 0 && deny_network` mistake.
// ---------------------------------------------------------------------------

#[test]
fn adversarial_ac5_symmetric_no_connect_must_not_block() {
    // A trace full of non-connect events. AC5 must not trigger.
    let events = vec![
        ev(1, "begin"),
        ev(2, "execve"),
        ev(3, "openat"),
        ev(4, "unlinkat"),
        ev(5, "execve"),
        ev(6, "openat"),
    ];
    let eval = evaluate(&events, &deny_net_only());

    assert_ne!(
        eval.verdict, "block",
        "deny_network claimed with ZERO connect events must not produce block; \
         got verdict={:?} for events={:?}",
        eval.verdict, events,
    );

    // And the constraint entry should report violated=false + connect_events=0.
    let entry = eval
        .map
        .get("deny_network")
        .expect("deny_network must be evaluated when claimed");
    let obj = entry.as_object().expect("deny_network must be an object");
    assert_eq!(
        obj.get("violated").and_then(serde_json::Value::as_bool),
        Some(false),
        "violated must be false when there are zero connect events",
    );
    assert_eq!(
        obj.get("connect_events").and_then(serde_json::Value::as_u64),
        Some(0),
        "connect_events must reflect zero observed connects",
    );
}

// ---------------------------------------------------------------------------
// Strategy 3: trivially-satisfying input.
// Empty events with deny_network=true: nothing was observed, nothing can be
// violated. Must NOT block.
// ---------------------------------------------------------------------------

#[test]
fn adversarial_ac5_empty_trace_must_not_block() {
    let eval = evaluate(&[], &deny_net_only());
    assert_ne!(
        eval.verdict, "block",
        "empty trace with deny_network claimed must not block (no connect observed)",
    );
    assert_eq!(eval.verdict, "pass", "the verdict for an empty trace must be pass");
    let entry = eval
        .map
        .get("deny_network")
        .expect("deny_network must appear in the map when claimed, even if no events");
    let obj = entry.as_object().unwrap();
    assert_eq!(
        obj.get("connect_events").and_then(serde_json::Value::as_u64),
        Some(0),
    );
    assert_eq!(
        obj.get("violated").and_then(serde_json::Value::as_bool),
        Some(false),
    );
}

// ---------------------------------------------------------------------------
// Strategy 4: inverted claim.
// AC5's precondition includes deny_network=true. If deny_network is NOT
// claimed, even a flood of connect events must not block (nor appear in the
// map). The existing acceptance test does check this once; we tighten it.
// ---------------------------------------------------------------------------

#[test]
fn adversarial_ac5_connects_without_claim_must_not_block() {
    let events = vec![ev(1, "connect"), ev(2, "connect"), ev(3, "connect")];
    let permissive = HardConstraints {
        deny_network: false,
        deny_unsafe_runtime: false,
        max_subprocess_depth: None,
    };
    let eval = evaluate(&events, &permissive);
    assert_ne!(
        eval.verdict, "block",
        "connect events with deny_network UNCLAIMED must not produce block",
    );
    assert!(
        !eval.map.contains_key("deny_network"),
        "unclaimed deny_network must not appear in constraints_evaluated, got map={:?}",
        eval.map,
    );
}

// ---------------------------------------------------------------------------
// Strategy 2: adjacent-value type collisions.
// AC5 names the event type "connect" (lowercase, exact). Values that LOOK
// like connect but are not must NOT trip the rule. This catches a careless
// substring match (`contains("connect")`) or a case-insensitive compare.
// ---------------------------------------------------------------------------

#[test]
fn adversarial_ac5_adjacent_event_types_must_not_block() {
    let cases = [
        "Connect",        // wrong case
        "CONNECT",        // wrong case
        "connecting",     // substring superset
        "preconnect",     // substring with prefix
        "connect2",       // typo'd numeric suffix
        "reconnect",      // wraps "connect"
        "disconnect",     // wraps "connect"
        "tcp_connect",    // namespaced variant
        " connect",       // leading whitespace
        "connect ",       // trailing whitespace
    ];
    for kind in &cases {
        let events = vec![ev(1, kind)];
        let eval = evaluate(&events, &deny_net_only());
        assert_ne!(
            eval.verdict, "block",
            "event type {kind:?} is not the literal \"connect\"; AC5 must not trigger",
        );
        let obj = eval
            .map
            .get("deny_network")
            .and_then(serde_json::Value::as_object)
            .expect("deny_network is claimed and must appear");
        assert_eq!(
            obj.get("connect_events").and_then(serde_json::Value::as_u64),
            Some(0),
            "connect_events count must be zero for non-\"connect\" type {kind:?}",
        );
    }
}

// ---------------------------------------------------------------------------
// Strategy 2b: adjacent boundary at the count threshold.
// AC5 says ">=1 connect event -> block". Test that exactly 1 trips it
// (Edit Agent's test covers this), and ALSO that 2 still trips it (catches
// a stub like `connect_events == 1`).
// ---------------------------------------------------------------------------

#[test]
fn adversarial_ac5_two_connects_still_block() {
    let events = vec![ev(1, "connect"), ev(2, "connect")];
    let eval = evaluate(&events, &deny_net_only());
    assert_eq!(
        eval.verdict, "block",
        ">=1 means 2 connects must still block; got verdict={:?}",
        eval.verdict,
    );
    let obj = eval
        .map
        .get("deny_network")
        .and_then(serde_json::Value::as_object)
        .expect("deny_network must appear");
    assert_eq!(
        obj.get("connect_events").and_then(serde_json::Value::as_u64),
        Some(2),
        "connect_events must reflect the actual observed count, not a saturated 1",
    );
    assert_eq!(
        obj.get("violated").and_then(serde_json::Value::as_bool),
        Some(true),
    );
}

// ---------------------------------------------------------------------------
// Strategy 5: output-shape check.
// Even when the verdict is "block", the receipt's deny_network entry must
// faithfully report claimed/violated/connect_events. This catches an impl
// that hardcodes the verdict string without populating the map honestly.
// ---------------------------------------------------------------------------

#[test]
fn adversarial_ac5_block_must_populate_map_honestly() {
    let events = vec![
        ev(1, "execve"),
        ev(2, "openat"),
        ev(3, "connect"), // the one that should trip it
        ev(4, "execve"),
    ];
    let eval = evaluate(&events, &deny_net_only());
    assert_eq!(eval.verdict, "block");

    let entry = eval
        .map
        .get("deny_network")
        .expect("deny_network entry must be present when the constraint is claimed");
    let obj = entry.as_object().expect("deny_network entry must be a JSON object");
    assert_eq!(
        obj.get("claimed").and_then(serde_json::Value::as_bool),
        Some(true),
        "claimed must be true",
    );
    assert_eq!(
        obj.get("violated").and_then(serde_json::Value::as_bool),
        Some(true),
        "violated must be true when >=1 connect is present",
    );
    assert_eq!(
        obj.get("connect_events").and_then(serde_json::Value::as_u64),
        Some(1),
        "connect_events must equal the actual observed count (1), not the total events (4)",
    );
}

// ---------------------------------------------------------------------------
// Strategy 1b: cross-constraint isolation.
// When ONLY deny_unsafe_runtime is claimed (deny_network not claimed),
// a connect event must not appear in the map under deny_network nor
// influence the verdict via the deny_network path. This guards against
// a stub that fires the deny_network rule whenever a connect is observed,
// regardless of whether deny_network was claimed.
// ---------------------------------------------------------------------------

#[test]
fn adversarial_ac5_unclaimed_constraint_isolation() {
    let events = vec![ev(1, "connect")];
    let only_unsafe_runtime = HardConstraints {
        deny_network: false,
        deny_unsafe_runtime: true,
        max_subprocess_depth: None,
    };
    let eval = evaluate(&events, &only_unsafe_runtime);
    assert!(
        !eval.map.contains_key("deny_network"),
        "deny_network is NOT claimed; it must not appear in the map even when a connect is observed",
    );
    // The lone connect event has no execve, so deny_unsafe_runtime is not
    // violated either; verdict should be pass.
    assert_eq!(
        eval.verdict, "pass",
        "unclaimed deny_network must not influence the verdict from a connect event",
    );
}
