//! Acceptance test for AC3 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: autobuilder-receipt (lib)
//! AC description: For any receipt written via write() and any single-field mutation (value swap, key add, key removal), the recomputed digest over the mutated payload differs from the stored digest. Proptest-driven; mutation kill rate target 100% on objects with at least one mutable field.
//! Test predicate: tests/acceptance_ac3_forgery_detection.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac3` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use autobuilder_receipt::{canonical_json_bytes, write};
use proptest::prelude::*;
use sha2::{Digest, Sha256};
use tempfile::NamedTempFile;

fn recompute(json: &serde_json::Value) -> String {
    let mut blanked = json.clone();
    if let Some(obj) = blanked.as_object_mut() {
        obj.insert(
            "receipt_digest".into(),
            serde_json::Value::String(String::new()),
        );
    }
    let canonical = canonical_json_bytes(&blanked);
    let mut hasher = Sha256::new();
    hasher.update(&canonical);
    format!("sha256:{:x}", hasher.finalize())
}

fn write_and_read(value: serde_json::Value) -> (String, serde_json::Value) {
    let tmp = NamedTempFile::new().unwrap();
    write(tmp.path(), value).unwrap();
    let bytes = std::fs::read(tmp.path()).unwrap();
    let parsed: serde_json::Value = serde_json::from_slice(&bytes).unwrap();
    let stored = parsed
        .get("receipt_digest")
        .and_then(serde_json::Value::as_str)
        .unwrap()
        .to_string();
    (stored, parsed)
}

#[test]
fn acceptance_ac3() {
    // Mutation 1: change an existing string field value.
    {
        let (stored, mut parsed) = write_and_read(serde_json::json!({
            "schema": "test.v1",
            "verdict": "pass",
        }));
        parsed
            .as_object_mut()
            .unwrap()
            .insert("verdict".into(), serde_json::Value::String("block".into()));
        assert_ne!(stored, recompute(&parsed), "value-swap must invalidate digest");
    }

    // Mutation 2: add a new key.
    {
        let (stored, mut parsed) = write_and_read(serde_json::json!({"a": 1}));
        parsed
            .as_object_mut()
            .unwrap()
            .insert("b".into(), serde_json::json!(2));
        assert_ne!(stored, recompute(&parsed), "key-add must invalidate digest");
    }

    // Mutation 3: remove an existing key.
    {
        let (stored, mut parsed) = write_and_read(serde_json::json!({"a": 1, "b": 2}));
        parsed.as_object_mut().unwrap().remove("b");
        assert_ne!(stored, recompute(&parsed), "key-removal must invalidate digest");
    }

    // Mutation 4: deep-nested edit.
    {
        let (stored, mut parsed) = write_and_read(serde_json::json!({
            "outer": {"inner": "before"},
        }));
        if let Some(v) = parsed.pointer_mut("/outer/inner") {
            *v = serde_json::Value::String("after".into());
        }
        assert_ne!(stored, recompute(&parsed), "deep edit must invalidate digest");
    }
}

proptest! {
    #[test]
    fn random_string_swap_invalidates_digest(
        seed_key in "[a-z]{1,8}",
        seed_value in "[a-zA-Z0-9]{1,16}",
        new_value in "[a-zA-Z0-9]{1,16}",
    ) {
        prop_assume!(seed_value != new_value);
        let (stored, mut parsed) = write_and_read(serde_json::json!({
            &seed_key: seed_value,
        }));
        parsed
            .as_object_mut()
            .unwrap()
            .insert(seed_key, serde_json::Value::String(new_value));
        prop_assert_ne!(stored, recompute(&parsed));
    }
}
