//! Acceptance test for AC4 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: autobuilder-receipt (lib)
//! AC description: write(path, value) returns Err whose message contains 'must be a JSON object' for each of: Null, Bool, Number, String, Array. No file is created when validation fails.
//! Test predicate: tests/acceptance_ac4_object_required.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac4` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use autobuilder_receipt::write;

#[test]
fn acceptance_ac4() {
    // Use a path under a fresh temp dir so we can verify "no file created on
    // validation failure" — the dir starts empty and must stay empty.
    let tmpdir = tempfile::tempdir().unwrap();
    let target = tmpdir.path().join("receipt.json");

    let bad_values = [
        serde_json::Value::Null,
        serde_json::Value::Bool(true),
        serde_json::Value::Bool(false),
        serde_json::json!(0),
        serde_json::json!(i64::MIN),
        serde_json::json!(""),
        serde_json::json!("x"),
        serde_json::json!([]),
        serde_json::Value::Array(vec![serde_json::Value::Null]),
    ];

    for bad in bad_values {
        let err = write(&target, bad.clone()).unwrap_err();
        let msg = format!("{err}");
        assert!(
            msg.contains("must be a JSON object"),
            "non-object {bad:?} must be rejected with diagnostic; got {msg:?}",
        );
        assert!(
            !target.exists(),
            "no file should be created when validation rejects {bad:?}",
        );
    }
}
