//! Acceptance test for AC5 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: autobuilder-receipt (lib)
//! AC description: secs_to_rfc3339(s) for any u64 s produces a 20-char string ending in Z with dashes at positions 4 and 7, T at position 10, colons at positions 13 and 16. Hand-fixture coverage of leap-year boundaries (2000-02-29, 2024-02-29, 2100-03-01) plus proptest on a wide u64 range.
//! Test predicate: tests/acceptance_ac5_rfc3339_format.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac5` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::doc_markdown,
    clippy::indexing_slicing
)]

use autobuilder_receipt::{now_rfc3339, secs_to_rfc3339};
use proptest::prelude::*;

fn assert_rfc3339_shape(ts: &str) {
    assert_eq!(ts.len(), 20, "RFC3339 UTC must be 20 chars: {ts:?}");
    assert!(ts.ends_with('Z'), "must end with Z: {ts:?}");
    let bytes = ts.as_bytes();
    assert_eq!(bytes[4], b'-', "char 4 must be '-': {ts:?}");
    assert_eq!(bytes[7], b'-', "char 7 must be '-': {ts:?}");
    assert_eq!(bytes[10], b'T', "char 10 must be 'T': {ts:?}");
    assert_eq!(bytes[13], b':', "char 13 must be ':': {ts:?}");
    assert_eq!(bytes[16], b':', "char 16 must be ':': {ts:?}");
}

#[test]
fn acceptance_ac5() {
    // Hand fixtures: epoch + leap-year boundaries + day boundaries.
    let cases = [
        (0_u64, "1970-01-01T00:00:00Z"),
        (1, "1970-01-01T00:00:01Z"),
        (86_399, "1970-01-01T23:59:59Z"),
        (86_400, "1970-01-02T00:00:00Z"),
        (951_782_400, "2000-02-29T00:00:00Z"),
        (951_868_800, "2000-03-01T00:00:00Z"),
        (1_709_164_800, "2024-02-29T00:00:00Z"),
        (1_709_251_200, "2024-03-01T00:00:00Z"),
        // 2100 is NOT a leap year (divisible by 100 but not 400). Feb 28 is the
        // last day; the day after rolls to March 1. The fixture below pins this
        // non-leap-century-boundary behavior, which a naive `% 4` check breaks.
        (4_107_456_000, "2100-02-28T00:00:00Z"),
        (4_107_542_400, "2100-03-01T00:00:00Z"),
    ];
    for (secs, expected) in cases {
        let got = secs_to_rfc3339(secs);
        assert_eq!(got, expected, "secs={secs}");
        assert_rfc3339_shape(&got);
    }

    let now = now_rfc3339().unwrap();
    assert_rfc3339_shape(&now);
    let year: u32 = now.get(..4).unwrap().parse().unwrap();
    assert!(
        (1970..=9999).contains(&year),
        "year out of plausible range: {now:?}",
    );
}

proptest! {
    #[test]
    fn format_invariants_on_wide_u64_range(secs in 0u64..253_402_300_799_u64) {
        let ts = secs_to_rfc3339(secs);
        assert_rfc3339_shape(&ts);
    }
}
