//! Acceptance test for AC1 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: autobuilder-receipt (lib)
//! AC description: Calling write(path, value) then parsing the on-disk JSON, blanking the receipt_digest field to empty string, and recomputing sha256(canonical_json_bytes(blanked)) produces a string byte-equal to the stored receipt_digest. Asserted on at least 3 hand-crafted receipt shapes (small flat, nested, with arrays).
//! Test predicate: tests/acceptance_ac1_self_binding.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac1` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use autobuilder_receipt::{canonical_json_bytes, write};
use sha2::{Digest, Sha256};
use tempfile::NamedTempFile;

fn recompute(json: &serde_json::Value) -> String {
    let mut blanked = json.clone();
    if let Some(obj) = blanked.as_object_mut() {
        obj.insert(
            "receipt_digest".into(),
            serde_json::Value::String(String::new()),
        );
    }
    let canonical = canonical_json_bytes(&blanked);
    let mut hasher = Sha256::new();
    hasher.update(&canonical);
    format!("sha256:{:x}", hasher.finalize())
}

fn assert_self_binds(value: serde_json::Value) {
    let tmp = NamedTempFile::new().unwrap();
    write(tmp.path(), value).unwrap();
    let bytes = std::fs::read(tmp.path()).unwrap();
    let parsed: serde_json::Value = serde_json::from_slice(&bytes).unwrap();
    let stored = parsed
        .get("receipt_digest")
        .and_then(serde_json::Value::as_str)
        .expect("receipt_digest must be present after write");
    let recomputed = recompute(&parsed);
    assert_eq!(stored, recomputed, "self-binding round-trip must hold");
    assert!(stored.starts_with("sha256:"));
    assert_eq!(stored.len(), 7 + 64, "sha256:<64-hex>");
}

#[test]
fn acceptance_ac1() {
    // Shape 1: small flat
    assert_self_binds(serde_json::json!({
        "schema": "test.v1",
        "verdict": "pass",
    }));

    // Shape 2: nested objects
    assert_self_binds(serde_json::json!({
        "schema": "test.v1",
        "details": {
            "nested": {"deep": "value", "n": 7},
            "count": 42,
        },
    }));

    // Shape 3: with arrays of mixed types
    assert_self_binds(serde_json::json!({
        "schema": "test.v1",
        "items": [1, "two", null, {"k": "v"}, [true, false]],
        "head_sha": "deadbeef" .repeat(5),
    }));
}
