//! Acceptance test for AC2 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: autobuilder-receipt (lib)
//! AC description: For any two serde_json::Value::Object values whose key/value pairs are identical multisets, canonical_json_bytes returns byte-identical output. Holds recursively on nested objects. Arrays preserve their original order (positional semantics; reordering changes the canonical bytes).
//! Test predicate: tests/acceptance_ac2_permutation_stable.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac2` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use autobuilder_receipt::canonical_json_bytes;
use proptest::prelude::*;

#[test]
fn acceptance_ac2() {
    let mut a = serde_json::Map::new();
    a.insert("zeta".into(), serde_json::json!(1));
    a.insert("alpha".into(), serde_json::json!(2));
    a.insert("mu".into(), serde_json::json!(3));
    let mut b = serde_json::Map::new();
    b.insert("mu".into(), serde_json::json!(3));
    b.insert("alpha".into(), serde_json::json!(2));
    b.insert("zeta".into(), serde_json::json!(1));
    assert_eq!(
        canonical_json_bytes(&serde_json::Value::Object(a)),
        canonical_json_bytes(&serde_json::Value::Object(b)),
        "flat objects with same multiset must canonicalize identically",
    );

    let nested_a = serde_json::json!({
        "outer": {"z": 1, "a": 2, "m": 3},
        "scalar": "x",
    });
    let nested_b = serde_json::json!({
        "scalar": "x",
        "outer": {"m": 3, "a": 2, "z": 1},
    });
    assert_eq!(
        canonical_json_bytes(&nested_a),
        canonical_json_bytes(&nested_b),
        "nested objects must canonicalize identically",
    );

    let arr_a = serde_json::json!({"x": [1, 2, 3]});
    let arr_b = serde_json::json!({"x": [3, 2, 1]});
    assert_ne!(
        canonical_json_bytes(&arr_a),
        canonical_json_bytes(&arr_b),
        "reordering array elements must change canonical bytes",
    );
}

proptest! {
    #[test]
    fn permutation_stable_under_random_key_orderings(
        pairs in proptest::collection::vec(("[a-z]{1,8}", any::<i32>()), 1..16)
    ) {
        let mut seen = std::collections::HashSet::new();
        let unique: Vec<_> = pairs
            .into_iter()
            .filter(|(k, _)| seen.insert(k.clone()))
            .collect();

        let mut forward = serde_json::Map::new();
        for (k, v) in &unique {
            forward.insert(k.clone(), serde_json::json!(v));
        }
        let mut reverse = serde_json::Map::new();
        for (k, v) in unique.iter().rev() {
            reverse.insert(k.clone(), serde_json::json!(v));
        }

        prop_assert_eq!(
            canonical_json_bytes(&serde_json::Value::Object(forward)),
            canonical_json_bytes(&serde_json::Value::Object(reverse)),
        );
    }
}
