//! Acceptance test for AC3 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: autobuilder-evolve-safety (lib)
//! AC description: Proptest invariant: for any synthesized diff body (random sequence of +, -, space lines inside a synthesized @@ hunk header), is_pure_addition_diff returns true iff no line inside any hunk body starts with -. Implementation and proptest spec agree on every generated sample.
//! Test predicate: tests/acceptance_ac3.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac3` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::doc_markdown,
    clippy::indexing_slicing
)]

use autobuilder_evolve_safety::is_pure_addition_diff;
use proptest::prelude::*;

/// Spec-side computation: independently derive "is pure-addition" from
/// the line sequence without delegating to the implementation. Two
/// independent encodings of the same predicate must agree on every
/// generated sample.
fn spec_is_pure_addition(diff_body: &str) -> bool {
    let mut in_hunk = false;
    for line in diff_body.lines() {
        if line.starts_with("@@") {
            in_hunk = true;
            continue;
        }
        if !in_hunk {
            continue;
        }
        if line.starts_with("---") || line.starts_with("+++") {
            in_hunk = false;
            continue;
        }
        if line.starts_with('-') {
            return false;
        }
    }
    true
}

/// Build a synthesized hunk body from a vector of (prefix, content) pairs
/// where prefix is one of ' ', '+', '-' and content is a random-ish
/// identifier.
fn synthesize(prefixes: &[char], content: &[String]) -> String {
    let mut out = String::new();
    out.push_str("--- a/foo\n+++ b/foo\n@@ -1,1 +1,1 @@\n");
    for (p, c) in prefixes.iter().zip(content.iter()) {
        out.push(*p);
        out.push_str(c);
        out.push('\n');
    }
    out
}

proptest! {
    #[test]
    fn impl_matches_spec_on_random_diffs(
        prefixes in proptest::collection::vec(prop_oneof![Just(' '), Just('+'), Just('-')], 0..32),
        content in proptest::collection::vec("[a-z0-9_/.-]{0,20}", 0..32),
    ) {
        // Truncate to the shorter of the two vectors so zip aligns cleanly.
        let n = prefixes.len().min(content.len());
        let p = &prefixes[..n];
        let c = &content[..n];
        let body = synthesize(p, c);
        prop_assert_eq!(is_pure_addition_diff(&body), spec_is_pure_addition(&body));
    }

    #[test]
    fn pure_plus_and_space_always_returns_true(
        prefixes in proptest::collection::vec(prop_oneof![Just(' '), Just('+')], 1..32),
        content in proptest::collection::vec("[a-z0-9_/.-]{0,20}", 1..32),
    ) {
        let n = prefixes.len().min(content.len());
        let body = synthesize(&prefixes[..n], &content[..n]);
        prop_assert!(is_pure_addition_diff(&body));
    }

    #[test]
    fn any_minus_line_returns_false(
        before in proptest::collection::vec(prop_oneof![Just(' '), Just('+')], 0..16),
        after in proptest::collection::vec(prop_oneof![Just(' '), Just('+'), Just('-')], 0..16),
        content_before in proptest::collection::vec("[a-z]{1,8}", 0..16),
        content_minus in "[a-z]{1,8}",
        content_after in proptest::collection::vec("[a-z]{1,8}", 0..16),
    ) {
        let nb = before.len().min(content_before.len());
        let na = after.len().min(content_after.len());
        let mut prefixes: Vec<char> = before[..nb].to_vec();
        let mut content: Vec<String> = content_before[..nb].to_vec();
        prefixes.push('-');
        content.push(content_minus);
        prefixes.extend(after[..na].iter().copied());
        content.extend(content_after[..na].iter().cloned());
        let body = synthesize(&prefixes, &content);
        prop_assert!(!is_pure_addition_diff(&body));
    }
}

#[test]
const fn acceptance_ac3() {
    // Sentinel: the proptest blocks above are the AC. This unit test just
    // anchors the test file in the AC-numbered cargo test list.
}
