//! Acceptance test for AC5 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: autobuilder-evolve-safety (lib)
//! AC description: Fingerprint sensitivity (proptest): any byte change in target, lines, or diff_body produces a different fingerprint. Reordering lines in appended_lines changes the fingerprint (order matters for digest binding).
//! Test predicate: tests/acceptance_ac5.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac5` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::path::PathBuf;

use autobuilder_evolve_safety::{append_fingerprint, patch_fingerprint};
use proptest::prelude::*;

proptest! {
    #[test]
    fn append_fingerprint_changes_on_target_change(
        target_a in "[a-z]{1,16}",
        target_b in "[a-z]{1,16}",
        lines in proptest::collection::vec("[a-z]{0,16}", 0..8),
    ) {
        prop_assume!(target_a != target_b);
        let lines: Vec<String> = lines.into_iter().collect();
        let fp_a = append_fingerprint(&PathBuf::from(&target_a), &lines);
        let fp_b = append_fingerprint(&PathBuf::from(&target_b), &lines);
        prop_assert_ne!(fp_a, fp_b);
    }

    #[test]
    fn append_fingerprint_changes_on_line_change(
        target in "[a-z]{1,16}",
        lines in proptest::collection::vec("[a-z]{1,16}", 1..8),
        new_last in "[a-z]{1,16}",
    ) {
        let mut mutated = lines.clone();
        if let Some(last) = mutated.last_mut() {
            prop_assume!(*last != new_last);
            *last = new_last;
        }
        let fp_a = append_fingerprint(&PathBuf::from(&target), &lines);
        let fp_b = append_fingerprint(&PathBuf::from(&target), &mutated);
        prop_assert_ne!(fp_a, fp_b);
    }

    #[test]
    fn append_fingerprint_order_sensitive(
        target in "[a-z]{1,16}",
        a in "[a-z]{1,8}",
        b in "[a-z]{1,8}",
    ) {
        prop_assume!(a != b);
        let forward = vec![a.clone(), b.clone()];
        let backward = vec![b, a];
        let fp_a = append_fingerprint(&PathBuf::from(&target), &forward);
        let fp_b = append_fingerprint(&PathBuf::from(&target), &backward);
        prop_assert_ne!(
            fp_a, fp_b,
            "swapping line order must change fingerprint (digest binding requires order)",
        );
    }

    #[test]
    fn patch_fingerprint_changes_on_diff_change(
        target in "[a-z]{1,16}",
        diff_a in "[a-z+@\\- /]{1,64}",
        diff_b in "[a-z+@\\- /]{1,64}",
    ) {
        prop_assume!(diff_a != diff_b);
        let fp_a = patch_fingerprint(&PathBuf::from(&target), &diff_a);
        let fp_b = patch_fingerprint(&PathBuf::from(&target), &diff_b);
        prop_assert_ne!(fp_a, fp_b);
    }
}

#[test]
const fn acceptance_ac5() {
    // Sentinel: the proptest blocks above are the AC. This unit test just
    // anchors the test file in the AC-numbered cargo test list.
}
