//! Acceptance test for AC1 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: autobuilder-evolve-safety (lib)
//! AC description: Hand-crafted diff bodies that ARE pure additions return true: single-hunk all-+/space, multi-hunk multi-file all-pure-additions, empty hunk body, diff with file headers but no @@.
//! Test predicate: tests/acceptance_ac1.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac1` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use autobuilder_evolve_safety::is_pure_addition_diff;

#[test]
fn acceptance_ac1() {
    // Case 1: empty input
    assert!(is_pure_addition_diff(""), "empty diff is vacuously pure-addition");

    // Case 2: file headers, no hunks
    assert!(
        is_pure_addition_diff("--- a/foo\n+++ b/foo\n"),
        "file headers only (no @@): vacuously pure-addition",
    );

    // Case 3: single hunk, all + and context
    let diff = "--- a/foo\n+++ b/foo\n@@ -1,3 +1,5 @@\n line1\n+inserted\n+inserted2\n line2\n line3\n";
    assert!(is_pure_addition_diff(diff), "single pure-addition hunk");

    // Case 4: multi-hunk, all pure-additions
    let multi = "\
--- a/foo
+++ b/foo
@@ -1,2 +1,3 @@
 a
+b
 c
@@ -10,2 +11,3 @@
 d
+e
 f
";
    assert!(is_pure_addition_diff(multi), "multi-hunk pure-addition");

    // Case 5: multi-file diff, both pure-additions
    let multi_file = "\
--- a/foo
+++ b/foo
@@ -1,1 +1,2 @@
 alpha
+beta
--- a/bar
+++ b/bar
@@ -1,1 +1,2 @@
 one
+two
";
    assert!(is_pure_addition_diff(multi_file), "multi-file pure-addition");

    // Case 6: empty hunk body (degenerate but valid)
    let empty_hunk = "--- a/foo\n+++ b/foo\n@@ -0,0 +0,0 @@\n";
    assert!(is_pure_addition_diff(empty_hunk), "empty hunk body is vacuously pure-addition");

    // Case 7: only context lines, no + or -
    let context_only = "--- a/foo\n+++ b/foo\n@@ -1,2 +1,2 @@\n alpha\n beta\n";
    assert!(is_pure_addition_diff(context_only), "context-only hunk is pure-addition");
}
