//! Acceptance test for AC2 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: autobuilder-evolve-safety (lib)
//! AC description: Hand-crafted diff bodies with - lines anywhere in any hunk body return false: single-hunk with one -, multi-hunk with - only in hunk 2, multi-file with + in file 1 and - in file 2, - immediately after @@, - immediately before the next file header.
//! Test predicate: tests/acceptance_ac2.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac2` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use autobuilder_evolve_safety::is_pure_addition_diff;

#[test]
fn acceptance_ac2() {
    // The load-bearing negatives. Any of these returning true is a destructive-edit bug.

    // Case 1: single hunk with one - line
    let one_minus = "\
--- a/foo
+++ b/foo
@@ -1,3 +1,2 @@
 alpha
-removed
 beta
";
    assert!(!is_pure_addition_diff(one_minus), "single - line must cause false");

    // Case 2: multi-hunk, - only in hunk 2
    let second_hunk_has_minus = "\
--- a/foo
+++ b/foo
@@ -1,2 +1,3 @@
 a
+b
 c
@@ -10,3 +11,2 @@
 d
-bad-line
 f
";
    assert!(
        !is_pure_addition_diff(second_hunk_has_minus),
        "- in later hunk must still cause false",
    );

    // Case 3: multi-file, + in file 1 and - in file 2
    let multi_file = "\
--- a/foo
+++ b/foo
@@ -1,1 +1,2 @@
 alpha
+beta
--- a/bar
+++ b/bar
@@ -1,2 +1,1 @@
 one
-two
";
    assert!(
        !is_pure_addition_diff(multi_file),
        "- in later file must cause false",
    );

    // Case 4: - immediately after @@
    let immediately_after = "--- a/foo\n+++ b/foo\n@@ -1,2 +1,1 @@\n-gone\n end\n";
    assert!(!is_pure_addition_diff(immediately_after));

    // Case 5: - immediately before next file header
    let before_next_file = "\
--- a/foo
+++ b/foo
@@ -1,2 +1,1 @@
 a
-b
--- a/bar
+++ b/bar
@@ -1,1 +1,2 @@
 only
+content
";
    assert!(!is_pure_addition_diff(before_next_file));

    // Case 6: only - lines (the worst case — a pure-deletion diff)
    let pure_deletion = "--- a/foo\n+++ /dev/null\n@@ -1,2 +0,0 @@\n-a\n-b\n";
    assert!(
        !is_pure_addition_diff(pure_deletion),
        "pure-deletion diff (file removal) MUST cause false; this is the load-bearing failure mode",
    );
}
