//! Acceptance test for AC4 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: autobuilder-evolve-safety (lib)
//! AC description: Fingerprint determinism: for any (target, appended_lines) pair, append_fingerprint returns the same 64-char lowercase hex string twice. Same for patch_fingerprint over (target, diff_body).
//! Test predicate: tests/acceptance_ac4.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac4` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::doc_markdown,
    clippy::similar_names
)]

use std::path::PathBuf;

use autobuilder_evolve_safety::{append_fingerprint, patch_fingerprint};

fn is_lowercase_hex(s: &str) -> bool {
    s.chars().all(|c| c.is_ascii_hexdigit() && !c.is_ascii_uppercase())
}

#[test]
fn acceptance_ac4() {
    let target = PathBuf::from("templates/scaffold/scripts/run-metrics.sh");
    let lines = vec!["line one".to_owned(), "line two".to_owned()];
    let diff = "--- a/x\n+++ b/x\n@@ -1,1 +1,2 @@\n a\n+b\n";

    // Determinism: same inputs → same output, twice.
    let fp1a = append_fingerprint(&target, &lines);
    let fp1b = append_fingerprint(&target, &lines);
    assert_eq!(fp1a, fp1b, "append_fingerprint must be deterministic");
    let fp2a = patch_fingerprint(&target, diff);
    let fp2b = patch_fingerprint(&target, diff);
    assert_eq!(fp2a, fp2b, "patch_fingerprint must be deterministic");

    // 64-char lowercase hex (sha256 hex length).
    for fp in [&fp1a, &fp2a] {
        assert_eq!(fp.len(), 64, "fingerprint must be 64 hex chars: {fp:?}");
        assert!(is_lowercase_hex(fp), "fingerprint must be lowercase hex: {fp:?}");
    }

    // The append and patch fingerprints of the same (target, content) shape
    // are not interchangeable — they hash different blobs by design.
    assert_ne!(
        fp1a, fp2a,
        "append and patch fingerprints must differ even on related inputs",
    );

    // Empty appended_lines is allowed and stable.
    let empty: Vec<String> = Vec::new();
    let fp_empty_a = append_fingerprint(&target, &empty);
    let fp_empty_b = append_fingerprint(&target, &empty);
    assert_eq!(fp_empty_a, fp_empty_b);
    assert_eq!(fp_empty_a.len(), 64);
}
