//! Acceptance test for AC6 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: autobuilder-evolve-safety (lib)
//! AC description: After subtree-merge into autobuilder/crates/evolve-safety/ and shim of the three in-bin call sites in evolve.rs, scripts/run-metrics.sh on the parent autobuilder repo reports ac_passing_count: 7/7. Two-key env-var gate: AUTOBUILDER_PARENT_REPO + AUTOBUILDER_EVOLVE_SAFETY_AC6_RUN_INTEGRATION.
//! Test predicate: tests/acceptance_ac6.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac6` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::doc_markdown,
    clippy::print_stderr
)]

use std::env;
use std::path::PathBuf;
use std::process::Command;

#[test]
fn acceptance_ac6() {
    // Two-key gate matches the pattern used by autobuilder-receipt's AC6
    // and autobuilder-gate's AC8. Both env vars must be set for the live
    // integration check; the live invocation strips both before spawning
    // so the nested cargo test --workspace inside the parent harness
    // re-enters this test with neither key and skips at the first guard.
    let Ok(parent) = env::var("AUTOBUILDER_PARENT_REPO") else {
        eprintln!(
            "AC6: AUTOBUILDER_PARENT_REPO not set; pending. \
             Set it AND AUTOBUILDER_EVOLVE_SAFETY_AC6_RUN_INTEGRATION=1 to run."
        );
        return;
    };
    if env::var("AUTOBUILDER_EVOLVE_SAFETY_AC6_RUN_INTEGRATION").is_err() {
        eprintln!(
            "AC6: AUTOBUILDER_EVOLVE_SAFETY_AC6_RUN_INTEGRATION not set; skipping \
             recursive integration shell-out."
        );
        return;
    }

    let parent = PathBuf::from(parent);
    assert!(parent.exists(), "AC6: parent repo {} not found", parent.display());

    let out = Command::new("bash")
        .arg(parent.join("scripts/run-metrics.sh"))
        .current_dir(&parent)
        .env_remove("AUTOBUILDER_PARENT_REPO")
        .env_remove("AUTOBUILDER_EVOLVE_SAFETY_AC6_RUN_INTEGRATION")
        .output()
        .expect("invoke parent run-metrics.sh");
    assert!(
        out.status.success(),
        "AC6: parent run-metrics.sh exited {}; stderr={}",
        out.status,
        String::from_utf8_lossy(&out.stderr),
    );
    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(
        stdout.contains("\"ac_passing_count\": 7"),
        "AC6: parent harness must report 7/7 ACs passing; stdout tail: {}",
        stdout.lines().rev().take(15).collect::<Vec<_>>().join("\n"),
    );
}
