//! Acceptance test for AC2 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: autobuilder-gate (lib)
//! AC description: Table-driven over all 8 specs: swapping the receipt's schema string to a wrong value causes check_receipt_value to return pass=false with a note containing 'schema mismatch'.
//! Test predicate: tests/acceptance_ac2.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac2` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use autobuilder_gate::{RECEIPT_SPECS, ReceiptSpec, check_receipt_value};

const HEAD: &str = "deadbeefcafebabe1234567890abcdef00000000";

fn happy_receipt(spec: &ReceiptSpec, head_sha: &str) -> serde_json::Value {
    let mut obj = serde_json::Map::new();
    obj.insert("schema".into(), spec.expected_schema.into());
    if spec.requires_head_match {
        obj.insert("head_sha".into(), head_sha.into());
    }
    if spec.name == "risk-gate" {
        obj.insert("blocking_count".into(), serde_json::json!(0));
    } else if spec.name == "reviewer-agent" {
        obj.insert(
            "decision".into(),
            spec.pass_verdicts.first().copied().unwrap_or("pass").into(),
        );
    } else if !spec.pass_verdicts.is_empty() {
        obj.insert(
            "verdict".into(),
            spec.pass_verdicts.first().copied().unwrap_or("pass").into(),
        );
    }
    serde_json::Value::Object(obj)
}

#[test]
fn acceptance_ac2() {
    for spec in RECEIPT_SPECS {
        let mut value = happy_receipt(spec, HEAD);
        value
            .as_object_mut()
            .unwrap()
            .insert("schema".into(), "wrong.schema.v0".into());

        let check = check_receipt_value(spec, &value, HEAD);

        assert!(
            !check.pass,
            "schema mismatch on {} must cause pass=false",
            spec.name,
        );
        assert!(
            check.notes.iter().any(|n| n.contains("schema mismatch")),
            "schema mismatch on {} must surface a 'schema mismatch' note; got {:?}",
            spec.name,
            check.notes,
        );
        assert_eq!(check.schema_observed.as_deref(), Some("wrong.schema.v0"));
        assert!(!check.schema_match);
    }
}
