//! Acceptance test for AC7 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: autobuilder-gate (lib)
//! AC description: check_receipt_at on a 0-byte file returns pass=false with a note containing 'empty'; on a non-JSON-parseable file returns pass=false with a note containing 'invalid JSON'; neither path panics.
//! Test predicate: tests/acceptance_ac7.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac7` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::io::Write as _;

use autobuilder_gate::{RECEIPT_SPECS, check_receipt_at};
use tempfile::NamedTempFile;

const HEAD: &str = "deadbeefcafebabe1234567890abcdef00000000";

const fn first_spec() -> &'static autobuilder_gate::ReceiptSpec {
    RECEIPT_SPECS.first().expect("RECEIPT_SPECS is non-empty")
}

#[test]
fn acceptance_ac7() {
    let spec = first_spec();

    // Missing file: present=false, "missing" note.
    let missing_path = std::path::PathBuf::from("/tmp/this-receipt-does-not-exist-XYZ.json");
    let check = check_receipt_at(spec, &missing_path, HEAD);
    assert!(!check.present);
    assert!(!check.pass);
    assert!(
        check.notes.iter().any(|n| n.contains("missing")),
        "missing file must surface 'missing' note; got {:?}",
        check.notes,
    );

    // Empty file: present=true, "empty" note, pass=false.
    let empty = NamedTempFile::new().unwrap();
    let check = check_receipt_at(spec, empty.path(), HEAD);
    assert!(check.present);
    assert!(!check.pass);
    assert!(
        check.notes.iter().any(|n| n.contains("empty")),
        "empty file must surface 'empty' note; got {:?}",
        check.notes,
    );

    // Non-JSON file: present=true, "invalid JSON" note, pass=false.
    let mut garbage = NamedTempFile::new().unwrap();
    garbage.write_all(b"this is { not valid \"json").unwrap();
    garbage.flush().unwrap();
    let check = check_receipt_at(spec, garbage.path(), HEAD);
    assert!(check.present);
    assert!(!check.pass);
    assert!(
        check.notes.iter().any(|n| n.contains("invalid JSON")),
        "non-JSON file must surface 'invalid JSON' note; got {:?}",
        check.notes,
    );

    // Truncated JSON (partial object): also "invalid JSON".
    let mut truncated = NamedTempFile::new().unwrap();
    truncated.write_all(b"{\"schema\":").unwrap();
    truncated.flush().unwrap();
    let check = check_receipt_at(spec, truncated.path(), HEAD);
    assert!(!check.pass);
    assert!(check.notes.iter().any(|n| n.contains("invalid JSON")));
}
