//! Acceptance test for AC4 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: autobuilder-gate (lib)
//! AC description: Proptest over RECEIPT_SPECS entries with non-empty pass_verdicts: any random verdict string not in pass_verdicts causes check_verdict to return false; any string in pass_verdicts returns true.
//! Test predicate: tests/acceptance_ac4.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac4` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use autobuilder_gate::{RECEIPT_SPECS, check_verdict};
use proptest::prelude::*;

#[test]
fn acceptance_ac4() {
    // Manual check: every spec with non-empty pass_verdicts: each allowlisted
    // string causes check_verdict to return true; one canonical "wrong"
    // string causes false.
    for spec in RECEIPT_SPECS {
        if spec.pass_verdicts.is_empty() {
            continue;
        }
        // risk-gate is special-cased (blocking_count semantics, not verdict),
        // and reviewer-agent reads decision not verdict — covered in AC5 and
        // by the proptest below. Here check only the verdict-based specs.
        if matches!(spec.name, "risk-gate" | "reviewer-agent") {
            continue;
        }
        for v in spec.pass_verdicts {
            let mut notes = Vec::new();
            assert!(
                check_verdict(spec, Some(v), None, None, &mut notes),
                "{}: allowlisted verdict {v:?} must return true (notes={:?})",
                spec.name,
                notes,
            );
        }
        let mut notes = Vec::new();
        assert!(
            !check_verdict(spec, Some("definitely-not-in-allowlist"), None, None, &mut notes),
            "{}: non-allowlisted verdict must return false",
            spec.name,
        );
    }
}

proptest! {
    #[test]
    fn random_verdicts_outside_allowlist_always_fail(s in "[a-zA-Z0-9_-]{1,32}") {
        for spec in RECEIPT_SPECS {
            if spec.pass_verdicts.is_empty() {
                continue;
            }
            if matches!(spec.name, "risk-gate" | "reviewer-agent") {
                continue;
            }
            if spec.pass_verdicts.iter().any(|p| *p == s) {
                // Skipped: random string happened to land on an allowlisted value.
                continue;
            }
            let mut notes = Vec::new();
            let ok = check_verdict(spec, Some(&s), None, None, &mut notes);
            prop_assert!(!ok, "{}: verdict {:?} not in {:?} but check returned true", spec.name, s, spec.pass_verdicts);
            prop_assert!(notes.iter().any(|n| n.contains("not in")),
                "{}: failure must surface diagnostic note", spec.name);
        }
    }

    #[test]
    fn reviewer_agent_decision_allowlist(s in "[a-zA-Z0-9_-]{1,32}") {
        let reviewer = RECEIPT_SPECS.iter().find(|s| s.name == "reviewer-agent").unwrap();
        let in_allow = reviewer.pass_verdicts.iter().any(|p| *p == s);
        let mut notes = Vec::new();
        let ok = check_verdict(reviewer, None, Some(&s), None, &mut notes);
        prop_assert_eq!(
            ok, in_allow,
            "reviewer decision={:?} allowlisted={} but check returned {}",
            s, in_allow, ok,
        );
    }
}
