//! Acceptance test for AC5 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: autobuilder-gate (lib)
//! AC description: risk-gate special-case (blocking_count semantics): blocking_count=0 passes, blocking_count>0 fails with a note containing 'blocking finding', blocking_count missing fails with a note containing 'missing'.
//! Test predicate: tests/acceptance_ac5.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac5` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use autobuilder_gate::{RECEIPT_SPECS, check_verdict};
use proptest::prelude::*;

fn risk_gate_spec() -> &'static autobuilder_gate::ReceiptSpec {
    RECEIPT_SPECS
        .iter()
        .find(|s| s.name == "risk-gate")
        .expect("risk-gate spec must be in RECEIPT_SPECS")
}

#[test]
fn acceptance_ac5() {
    let spec = risk_gate_spec();

    // blocking_count = 0 → pass, no failure note
    let mut notes = Vec::new();
    assert!(
        check_verdict(spec, None, None, Some(0), &mut notes),
        "blocking_count=0 must pass; notes={notes:?}",
    );
    assert!(notes.is_empty(), "passing path must not push notes");

    // blocking_count > 0 → fail with "blocking finding" note
    for n in [1_i64, 2, 7, 100, 1_000] {
        let mut notes = Vec::new();
        assert!(
            !check_verdict(spec, None, None, Some(n), &mut notes),
            "blocking_count={n} must fail",
        );
        assert!(
            notes.iter().any(|note| note.contains("blocking finding")),
            "blocking_count={n} must surface 'blocking finding' note; got {notes:?}",
        );
    }

    // blocking_count missing → fail with "missing" note
    let mut notes = Vec::new();
    assert!(
        !check_verdict(spec, None, None, None, &mut notes),
        "missing blocking_count must fail",
    );
    assert!(
        notes.iter().any(|note| note.contains("missing")),
        "missing blocking_count must surface 'missing' note; got {notes:?}",
    );
}

proptest! {
    #[test]
    fn risk_gate_pass_iff_blocking_count_zero(n in 0_i64..=10_000) {
        let spec = risk_gate_spec();
        let mut notes = Vec::new();
        let ok = check_verdict(spec, None, None, Some(n), &mut notes);
        prop_assert_eq!(ok, n == 0,
            "blocking_count={} expected pass={} got pass={}", n, n == 0, ok);
    }
}
