//! Acceptance test for AC6 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: autobuilder-gate (lib)
//! AC description: Proptest: aggregate is permutation-invariant. For any Vec<ReceiptCheck> of length 1..16, aggregate(shuffled) returns the same (pass_count, block_count, verdict) triple as aggregate(original).
//! Test predicate: tests/acceptance_ac6.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac6` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use autobuilder_gate::{ReceiptCheck, aggregate};
use proptest::prelude::*;

fn make_check(pass: bool, idx: usize) -> ReceiptCheck {
    let name: &'static str = match idx % 8 {
        0 => "intake",
        1 => "vti-plan",
        2 => "proof-receipt",
        3 => "risk-gate",
        4 => "reviewer-agent",
        5 => "rollback-plan",
        6 => "ci-checks",
        _ => "session-trace",
    };
    ReceiptCheck {
        name,
        path: String::new(),
        present: pass,
        schema_expected: "test.v1",
        schema_observed: Some("test.v1".into()),
        schema_match: pass,
        head_sha_required: false,
        head_sha_observed: None,
        head_sha_match: true,
        verdict_observed: None,
        decision_observed: None,
        blocking_count_observed: None,
        receipt_digest_observed: None,
        pass,
        notes: Vec::new(),
    }
}

#[test]
fn acceptance_ac6_manual() {
    // Manual: 8 checks, last one fails. Aggregate same regardless of order.
    let mut checks: Vec<_> = (0..8).map(|i| make_check(i != 7, i)).collect();
    let (p1, b1, v1) = aggregate(&checks);
    assert_eq!((p1, b1, v1), (7, 1, "block"));
    checks.reverse();
    let (p2, b2, v2) = aggregate(&checks);
    assert_eq!((p2, b2, v2), (p1, b1, v1));
    // All-pass → "pass"
    let all_pass: Vec<_> = (0..5).map(|i| make_check(true, i)).collect();
    assert_eq!(aggregate(&all_pass), (5, 0, "pass"));
    // Empty input edge case: 0 checks → 0/0 → "pass" (vacuously true).
    assert_eq!(aggregate(&[]), (0, 0, "pass"));
}

proptest! {
    #[test]
    fn aggregate_permutation_invariant(
        passes in proptest::collection::vec(any::<bool>(), 1..16),
    ) {
        let original: Vec<_> = passes
            .iter()
            .enumerate()
            .map(|(i, &p)| make_check(p, i))
            .collect();
        let mut shuffled = original.clone();
        shuffled.reverse();

        let (pa, ba, va) = aggregate(&original);
        let (pb, bb, vb) = aggregate(&shuffled);
        prop_assert_eq!((pa, ba, va), (pb, bb, vb));

        // And against another deterministic permutation: interleave halves.
        let mid = original.len() / 2;
        let (first, second) = original.split_at(mid);
        let mut interleaved = Vec::with_capacity(original.len());
        let mut it_a = first.iter();
        let mut it_b = second.iter();
        loop {
            match (it_a.next(), it_b.next()) {
                (Some(a), Some(b)) => { interleaved.push(a.clone()); interleaved.push(b.clone()); }
                (Some(a), None) => interleaved.push(a.clone()),
                (None, Some(b)) => interleaved.push(b.clone()),
                (None, None) => break,
            }
        }
        let (pc, bc, vc) = aggregate(&interleaved);
        prop_assert_eq!((pa, ba, va), (pc, bc, vc));
    }

    #[test]
    fn any_failing_check_blocks(
        passes in proptest::collection::vec(any::<bool>(), 1..16),
    ) {
        let checks: Vec<_> = passes
            .iter()
            .enumerate()
            .map(|(i, &p)| make_check(p, i))
            .collect();
        let (_pass, block, verdict) = aggregate(&checks);
        let expected_block = passes.iter().filter(|p| !**p).count();
        prop_assert_eq!(block, expected_block);
        prop_assert_eq!(verdict, if expected_block == 0 { "pass" } else { "block" });
    }
}
