//! Acceptance test for AC3 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: autobuilder-gate (lib)
//! AC description: Table-driven over specs with requires_head_match=true: mutating head_sha to any sibling sha causes check_receipt_value to return pass=false with a note containing 'head_sha mismatch'.
//! Test predicate: tests/acceptance_ac3.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac3` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use autobuilder_gate::{RECEIPT_SPECS, ReceiptSpec, check_receipt_value};

const HEAD: &str = "deadbeefcafebabe1234567890abcdef00000000";
const SIBLING: &str = "feedface0000000000000000000000000000beef";

fn happy_receipt(spec: &ReceiptSpec, head_sha: &str) -> serde_json::Value {
    let mut obj = serde_json::Map::new();
    obj.insert("schema".into(), spec.expected_schema.into());
    if spec.requires_head_match {
        obj.insert("head_sha".into(), head_sha.into());
    }
    if spec.name == "risk-gate" {
        obj.insert("blocking_count".into(), serde_json::json!(0));
    } else if spec.name == "reviewer-agent" {
        obj.insert(
            "decision".into(),
            spec.pass_verdicts.first().copied().unwrap_or("pass").into(),
        );
    } else if !spec.pass_verdicts.is_empty() {
        obj.insert(
            "verdict".into(),
            spec.pass_verdicts.first().copied().unwrap_or("pass").into(),
        );
    }
    serde_json::Value::Object(obj)
}

#[test]
fn acceptance_ac3() {
    let mut covered = 0_usize;
    for spec in RECEIPT_SPECS {
        if !spec.requires_head_match {
            // intake + risk-gate skip head_sha; not in scope for this AC.
            continue;
        }
        covered += 1;

        // Case A: head_sha mutated to a sibling sha
        let mut value = happy_receipt(spec, HEAD);
        value
            .as_object_mut()
            .unwrap()
            .insert("head_sha".into(), SIBLING.into());
        let check = check_receipt_value(spec, &value, HEAD);
        assert!(
            !check.pass,
            "head_sha mutation on {} must cause pass=false",
            spec.name,
        );
        assert!(
            check.notes.iter().any(|n| n.contains("head_sha mismatch")),
            "{} must surface 'head_sha mismatch' note; got {:?}",
            spec.name,
            check.notes,
        );

        // Case B: head_sha removed entirely
        let mut value = happy_receipt(spec, HEAD);
        value.as_object_mut().unwrap().remove("head_sha");
        let check = check_receipt_value(spec, &value, HEAD);
        assert!(
            !check.pass,
            "missing head_sha on {} (required) must cause pass=false",
            spec.name,
        );
        assert!(
            check.notes.iter().any(|n| n.contains("missing `head_sha`")),
            "{} must surface 'missing head_sha' note; got {:?}",
            spec.name,
            check.notes,
        );
    }
    assert!(
        covered >= 6,
        "AC3 must cover at least 6 receipts with requires_head_match=true; covered {covered}",
    );
}
