//! Acceptance test for AC1 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: autobuilder-gate (lib)
//! AC description: Synthesizing 8 valid receipts (one per RECEIPT_SPECS entry) with correct schema, matching head_sha, and pass-verdict each yields check.pass=true for every check, and aggregate returns (pass_count=8, block_count=0, verdict='pass').
//! Test predicate: tests/acceptance_ac1.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac1` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use autobuilder_gate::{
    RECEIPT_SPECS, ReceiptSpec, aggregate, check_receipt_value,
};

const HEAD: &str = "deadbeefcafebabe1234567890abcdef00000000";

/// Build a happy-path receipt JSON for the given spec.
fn happy_receipt(spec: &ReceiptSpec, head_sha: &str) -> serde_json::Value {
    let mut obj = serde_json::Map::new();
    obj.insert("schema".into(), spec.expected_schema.into());
    if spec.requires_head_match {
        obj.insert("head_sha".into(), head_sha.into());
    }
    // risk-gate uses blocking_count, not verdict.
    if spec.name == "risk-gate" {
        obj.insert("blocking_count".into(), serde_json::json!(0));
    } else if spec.name == "reviewer-agent" {
        // reviewer-agent uses decision, not verdict.
        let d = spec
            .pass_verdicts
            .first()
            .copied()
            .unwrap_or("pass");
        obj.insert("decision".into(), d.into());
    } else if !spec.pass_verdicts.is_empty() {
        let v = spec.pass_verdicts.first().copied().unwrap_or("pass");
        obj.insert("verdict".into(), v.into());
    }
    serde_json::Value::Object(obj)
}

#[test]
fn acceptance_ac1() {
    assert_eq!(
        RECEIPT_SPECS.len(),
        25,
        "spec table size: 8 originals + 17 extended-gates"
    );

    let checks: Vec<_> = RECEIPT_SPECS
        .iter()
        .map(|spec| check_receipt_value(spec, &happy_receipt(spec, HEAD), HEAD))
        .collect();

    for check in &checks {
        assert!(
            check.pass,
            "happy-path receipt for {} must pass; notes={:?}",
            check.name, check.notes,
        );
    }

    let (pass, block, verdict) = aggregate(&checks);
    assert_eq!(pass, 25);
    assert_eq!(block, 0);
    assert_eq!(verdict, "pass");
}
